### ISSUE TITLE
Feature: Nginx-level implementation of Onion-Location

### ISSUE THREAD

**Issue by Kixunil** [Kixunil/cryptoanarchy-deb-repo-builder#117]
**Is your feature request related to a problem? Please describe.**
`Onion-Location` can inform users using Tor browser to switch to onion site. This is already implemented by BTCPayServer. 

**Describe the solution you'd like**
Add `Onion-Location` to our Nginx configuration.

**Describe alternatives you've considered**
* Add this to every app - inefficient
* Don't add this - it should be reasonably easy to do, so why not?

**Additional context**
See also https://github.com/btcpayserver/btcpayserver/discussions/2220 - this is not a replacement though, BTCPayServer still shows onion in the UI.

**Implementation notes**
We should also improve configurability of our nginx setup.
So we make sure to include `onion-conf.d` directory from `onion` sites and `clearnet-conf.d` from clearnet sites. (Detecting TLD should be fine, but a bit messy due to mustache.)
`selfhost-onion` will generate a file in `clearnet-conf.d` containing `set_header Onion-Location ...` if it doesn't exist. This will allow the user to override it if needed.

**Comment by MaxHillebrand** [comment]
concept ACK, would use in production, thanks.

**Comment by Kixunil** [comment]
Sadly, this breaks shitton of stuff as onion now has to fill `is_onion = true`, the changed interface means changing `selfhost` version to 0.2 and all apps recommend `selfhost (<< 0.2)`. I think I will use `conflicts` for now but this is not a great design and **should** be changed in the future.
