### ISSUE TITLE
Install error "Minimum supported rustc version is 1.31"

### ISSUE THREAD

**Issue by Fonta1n3** [Kixunil/cryptoanarchy-deb-repo-builder#22]
Initial setup failed for me. Using debian stretch I ran `sudo apt-get install cargo` then
`cargo install --bin gen_deb_repository --git https://github.com/Kixunil/debcrafter`
And got the following error:
```
error: failed to compile `debcrafter v0.1.1 (https://github.com/Kixunil/debcrafter#0735baea)`, intermediate artifacts can be found at `/tmp/cargo-install.c2fmHOs2t1
J7`
Caused by:
  failed to run custom build command for `proc-macro2 v1.0.6`
process didn't exit successfully: `/tmp/cargo-install.c2fmHOs2t1J7/release/build/proc-macro2-9384f7040fb9d704/build-script-build` (exit code: 1)
--- stdout
cargo:rerun-if-changed=build.rs
--- stderr
Minimum supported rustc version is 1.31
```

Do you know how I can fix it?

**Comment by Kixunil** [comment]
Ah, sure, the instructions are for Debian Buster, but it should work for Stretch if you install newer version. I don't know if it's in backports repository. If not, you can simply uninistall it and use [rustup](https://rustup.rs) to install Rust instead.

**Comment by Kixunil** [comment]
I've documented the minimum version and I don't think it makes much sense to support older right now. If you decide to try it with a newer version I'd appreciate feedback.
