### ISSUE TITLE
Connect LND to BTCPayServer

### ISSUE THREAD

**Issue by Kixunil** [Kixunil/cryptoanarchy-deb-repo-builder#52]
There's currently no code to connect LND to BTCPayServer automatically. While it'd be easy to hack something together, I feel that this is the right time to finally implement debinteg and do it properly.

But I'm willing to quickly hack it if there's a strong enough pressure.

**Comment by nixbitcoin** [comment]
How come you're not using the `admin.macaroon`?

**Comment by nixbitcoin** [comment]
How are you passing the lnd connection string to BTCPayServer?

**Comment by Kixunil** [comment]
The `lnd-genmacaroon` package contains a simple script that generates union(info.macaroon, readonly.macaroon) and that one is stored in a location which is only accessible by users that are both in `lnd-system-{network}-readonly` and `lnd-system-{network}-invoice` groups.

The connection string is generated [here](https://github.com/Kixunil/cryptoanarchy-deb-repo-builder/commit/143293caa4b4504ae54af30471bcb50f8401a23b#diff-f93bdd76dba95273ae49509c2cd42253R18) the file is then concatenated to the resulting config file (I use this technique for all apps that don't support conf dirs natively)
